"""init

Revision ID: f3e0d2d00aeb
Revises: 
Create Date: 2024-04-08 14:59:08.021046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e0d2d00aeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_real_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMINISTRATOR', name='role'), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user')),
    sa.UniqueConstraint('thread_id', name=op.f('uq_user_thread_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_user_id'))
    )
    op.create_table('floodapplication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('details', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('form', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('documents', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('pdf_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONFIRMED', 'DECLINED', 'COMPLETED', name='status'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('moder_message_id', sa.Integer(), nullable=True),
    sa.Column('user_message_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_floodapplication_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floodapplication')),
    sa.UniqueConstraint('moder_message_id', name=op.f('uq_floodapplication_moder_message_id')),
    sa.UniqueConstraint('pdf_id', name=op.f('uq_floodapplication_pdf_id')),
    sa.UniqueConstraint('user_message_id', name=op.f('uq_floodapplication_user_message_id'))
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('user_message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_question_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question')),
    sa.UniqueConstraint('user_message_id', name=op.f('uq_question_user_message_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('floodapplication')
    op.drop_table('user')
    # ### end Alembic commands ###
